language: node_js

node_js:
  - "8"
  
script:
  - npm run danger
  - npm test
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error
  - npm run compile
  - npm run test:compiled
  - npm run filesize

